"use strict";

window.THEME_2_DATA = {
  id: 2,
  title: "Language & Communication",
  icon: "🌍",
  vocabulary: [
    { id: 1, lesson: "1", title: "How do we use language?", word: "bilingual", speak: "bilingual", ipa: "/baɪˈlɪŋɡwəl/", pos: "Adj / N", meaning: "Song ngữ; người sử dụng hai ngôn ngữ", example: "A bilingual student can explain the idea in both English and Vietnamese.", icon: "🗣️" },
    { id: 2, lesson: "1", title: "How do we use language?", word: "ideogram", speak: "ideogram", ipa: "/ˈɪdiəɡræm/", pos: "N", meaning: "Ký hiệu biểu ý; chữ tượng ý", example: "A heart icon can work as an ideogram for love.", icon: "㊗️" },
    { id: 3, lesson: "1", title: "How do we use language?", word: "mother tongue", speak: "mother tongue", ipa: "/ˌmʌðə ˈtʌŋ/", pos: "NP", meaning: "Tiếng mẹ đẻ", example: "Vietnamese is Lan's mother tongue.", icon: "🏠" },
    { id: 4, lesson: "1", title: "How do we use language?", word: "multilingual", speak: "multilingual", ipa: "/ˌmʌltiˈlɪŋɡwəl/", pos: "Adj / N", meaning: "Đa ngôn ngữ; người sử dụng nhiều ngôn ngữ", example: "The airport uses multilingual signs for international travellers.", icon: "🌐" },
    { id: 5, lesson: "1", title: "How do we use language?", word: "interpreter", speak: "interpreter", ipa: "/ɪnˈtɜːprɪtə/", pos: "N", meaning: "Phiên dịch viên", example: "The interpreter translated the speaker's words during the meeting.", icon: "🎧" },
    { id: 6, lesson: "1", title: "How do we use language?", word: "translator", speak: "translator", ipa: "/trænzˈleɪtə/", pos: "N", meaning: "Biên dịch viên", example: "A translator changes written text from one language into another.", icon: "📝" },
    { id: 7, lesson: "1", title: "How do we use language?", word: "dialect", speak: "dialect", ipa: "/ˈdaɪəlekt/", pos: "N", meaning: "Phương ngữ; tiếng địa phương", example: "People in different regions may speak the same language with a different dialect.", icon: "🗺️" },
    { id: 8, lesson: "1", title: "How do we use language?", word: "extinct", speak: "extinct", ipa: "/ɪkˈstɪŋkt/", pos: "Adj", meaning: "Tuyệt chủng; không còn tồn tại", example: "A language becomes extinct when nobody speaks it anymore.", icon: "🦖" },
    { id: 9, lesson: "2", title: "Communication without words", word: "fidget", speak: "fidget", ipa: "/ˈfɪdʒɪt/", pos: "V", meaning: "Cựa quậy; bồn chồn không yên", example: "Try not to fidget while your partner is speaking.", icon: "🫨" },
    { id: 10, lesson: "2", title: "Communication without words", word: "expression", speak: "expression", ipa: "/ɪkˈspreʃn/", pos: "N", meaning: "Biểu cảm; nét mặt", example: "His worried expression showed that something was wrong.", icon: "😟" },
    { id: 11, lesson: "2", title: "Communication without words", word: "gesture", speak: "gesture", ipa: "/ˈdʒestʃə/", pos: "N", meaning: "Cử chỉ; điệu bộ", example: "She made a welcoming gesture with her hand.", icon: "👋" },
    { id: 12, lesson: "2", title: "Communication without words", word: "emotion", speak: "emotion", ipa: "/ɪˈməʊʃn/", pos: "N", meaning: "Cảm xúc", example: "Facial movements can communicate emotion without words.", icon: "💗" },
    { id: 13, lesson: "2", title: "Communication without words", word: "possess", speak: "possess", ipa: "/pəˈzes/", pos: "V", meaning: "Sở hữu; có", example: "Humans possess the ability to communicate in many ways.", icon: "🧠" },
    { id: 14, lesson: "2", title: "Communication without words", word: "mysterious", speak: "mysterious", ipa: "/mɪˈstɪəriəs/", pos: "Adj", meaning: "Bí ẩn; khó hiểu", example: "The stranger's silent smile seemed mysterious.", icon: "🕵️" },
    { id: 15, lesson: "2", title: "Communication without words", word: "shrug", speak: "shrug", ipa: "/ʃrʌɡ/", pos: "V", meaning: "Nhún vai", example: "He shrugged because he did not know the answer.", icon: "🤷" },
    { id: 16, lesson: "2", title: "Communication without words", word: "stare", speak: "stare", ipa: "/steə/", pos: "V", meaning: "Nhìn chằm chằm", example: "It is impolite to stare at someone for a long time.", icon: "👀" },
    { id: 17, lesson: "2", title: "Communication without words", word: "intensity", speak: "intensity", ipa: "/ɪnˈtensəti/", pos: "N", meaning: "Cường độ; mức độ mạnh mẽ", example: "The intensity of her voice showed how strongly she felt.", icon: "🔥" },
    { id: 18, lesson: "2", title: "Communication without words", word: "indication", speak: "indication", ipa: "/ˌɪndɪˈkeɪʃn/", pos: "N", meaning: "Dấu hiệu; sự chỉ dẫn", example: "A nod can be an indication of agreement.", icon: "✅" },
    { id: 19, lesson: "2", title: "Communication without words", word: "irritate", speak: "irritate", ipa: "/ˈɪrɪteɪt/", pos: "V", meaning: "Làm khó chịu; chọc tức", example: "Constant tapping can irritate the people around you.", icon: "😠" },
    { id: 20, lesson: "2", title: "Communication without words", word: "regret", speak: "regret", ipa: "/rɪˈɡret/", pos: "V", meaning: "Hối tiếc; lấy làm tiếc", example: "I regret interrupting you during the discussion.", icon: "😔" },
    { id: 21, lesson: "2", title: "Communication without words", word: "technique", speak: "technique", ipa: "/tekˈniːk/", pos: "N", meaning: "Kỹ thuật; phương pháp", example: "Mirroring a speaker's posture is a communication technique.", icon: "🛠️" },
    { id: 22, lesson: "2", title: "Communication without words", word: "chaos", speak: "chaos", ipa: "/ˈkeɪɒs/", pos: "N", meaning: "Sự hỗn loạn", example: "Without clear instructions, the group discussion turned into chaos.", icon: "🌪️" },
    { id: 23, lesson: "2", title: "Communication without words", word: "disbelief", speak: "disbelief", ipa: "/ˌdɪsbɪˈliːf/", pos: "N", meaning: "Sự không tin; sự sửng sốt", example: "She raised her eyebrows in disbelief.", icon: "😲" },
    { id: 24, lesson: "2", title: "Communication without words", word: "coast", speak: "coast", ipa: "/kəʊst/", pos: "N", meaning: "Bờ biển; vùng duyên hải", example: "Some gestures have different meanings along the coast.", icon: "🏖️" },
    { id: 25, lesson: "2", title: "Communication without words", word: "be proud of", speak: "be proud of", ipa: "/biː ˈpraʊd əv/", pos: "AdjP", meaning: "Tự hào về", example: "You should be proud of your ability to learn another language.", icon: "🏆" },
    { id: 26, lesson: "4", title: "How is communication changing?", word: "stationery", speak: "stationery", ipa: "/ˈsteɪʃənri/", pos: "N", meaning: "Văn phòng phẩm; giấy viết thư", example: "I bought colourful stationery to write a letter to my pen friend.", icon: "✏️" },
    { id: 27, lesson: "4", title: "How is communication changing?", word: "slang", speak: "slang", ipa: "/slæŋ/", pos: "N", meaning: "Tiếng lóng", example: "The word cool is common slang in informal conversations.", icon: "😎" },
    { id: 28, lesson: "5", title: "Is letter writing a thing of the past?", word: "salutation", speak: "salutation", ipa: "/ˌsæljuˈteɪʃn/", pos: "N", meaning: "Lời chào mở đầu thư hoặc email", example: "Dear Ms Brown is a formal salutation.", icon: "👋" },
    { id: 29, lesson: "5", title: "Is letter writing a thing of the past?", word: "snail mail", speak: "snail mail", ipa: "/ˈsneɪl meɪl/", pos: "NP", meaning: "Thư gửi qua bưu điện; thư truyền thống", example: "My grandmother still enjoys sending birthday cards by snail mail.", icon: "🐌" },
    { id: 30, lesson: "5", title: "Is letter writing a thing of the past?", word: "sign off", speak: "sign off", ipa: "/ˌsaɪn ˈɒf/", pos: "VP", meaning: "Kết thư; kết thúc thư hoặc email", example: "You can sign off a friendly email with Best wishes.", icon: "✍️" },
    { id: 31, lesson: "6", title: "Communication with photos", word: "airbrush", speak: "airbrush", ipa: "/ˈeəbrʌʃ/", pos: "V / N", meaning: "Chỉnh sửa ảnh để làm đẹp; dụng cụ phun màu", example: "Some magazines airbrush photos to make skin look smoother.", icon: "🖌️" },
    { id: 32, lesson: "6", title: "Communication with photos", word: "take a selfie", speak: "take a selfie", ipa: "/ˌteɪk ə ˈselfi/", pos: "VP", meaning: "Chụp ảnh tự sướng", example: "The friends took a selfie in front of the science museum.", icon: "🤳" },
    { id: 33, lesson: "6", title: "Communication with photos", word: "beneficial", speak: "beneficial", ipa: "/ˌbenɪˈfɪʃl/", pos: "Adj", meaning: "Có lợi; hữu ích", example: "Sharing a useful diagram can be beneficial for visual learners.", icon: "🌱" },
    { id: 34, lesson: "6", title: "Communication with photos", word: "insightful", speak: "insightful", ipa: "/ˈɪnsaɪtfl/", pos: "Adj", meaning: "Sâu sắc; đem lại hiểu biết mới", example: "The photo essay offered an insightful view of daily life.", icon: "💡" },
    { id: 35, lesson: "6", title: "Communication with photos", word: "awareness", speak: "awareness", ipa: "/əˈweənəs/", pos: "N", meaning: "Nhận thức; sự hiểu biết", example: "The campaign uses images to raise awareness of ocean pollution.", icon: "👁️" },
    { id: 36, lesson: "6", title: "Communication with photos", word: "visual language", speak: "visual language", ipa: "/ˌvɪʒuəl ˈlæŋɡwɪdʒ/", pos: "NP", meaning: "Ngôn ngữ hình ảnh", example: "Colours and symbols are part of visual language.", icon: "🎨" },
    { id: 37, lesson: "7", title: "Mobile technology and communication", word: "distraction", speak: "distraction", ipa: "/dɪˈstrækʃn/", pos: "N", meaning: "Sự xao nhãng; điều gây mất tập trung", example: "A buzzing phone can be a distraction during a conversation.", icon: "📱" },
    { id: 38, lesson: "7", title: "Mobile technology and communication", word: "concentrate / concentration", speak: "concentrate, concentration", ipa: "/ˈkɒnsntreɪt/ · /ˌkɒnsnˈtreɪʃn/", pos: "V / N", meaning: "Tập trung / sự tập trung", example: "I turn off notifications so I can concentrate and improve my concentration.", icon: "🎯" },
    { id: 39, lesson: "7", title: "Mobile technology and communication", word: "manner", speak: "manner", ipa: "/ˈmænə/", pos: "N", meaning: "Cách thức; cách cư xử", example: "Please speak in a calm and respectful manner.", icon: "🤝" },
    { id: 40, lesson: "7", title: "Mobile technology and communication", word: "interrupt", speak: "interrupt", ipa: "/ˌɪntəˈrʌpt/", pos: "V", meaning: "Ngắt lời; làm gián đoạn", example: "Wait for a pause instead of interrupting the speaker.", icon: "✋" },
    { id: 41, lesson: "7", title: "Mobile technology and communication", word: "scroll", speak: "scroll", ipa: "/skrəʊl/", pos: "V", meaning: "Cuộn màn hình", example: "Do not scroll through your phone while someone is talking to you.", icon: "📜" },
    { id: 42, lesson: "7", title: "Mobile technology and communication", word: "element", speak: "element", ipa: "/ˈelɪmənt/", pos: "N", meaning: "Yếu tố; thành phần", example: "Eye contact is an important element of face-to-face communication.", icon: "🧩" },
    { id: 43, lesson: "7", title: "Mobile technology and communication", word: "ensure", speak: "ensure", ipa: "/ɪnˈʃʊə/", pos: "V", meaning: "Đảm bảo; chắc chắn rằng", example: "Repeat the meeting time to ensure everyone understands.", icon: "🔒" },
    { id: 44, lesson: "7", title: "Mobile technology and communication", word: "success", speak: "success", ipa: "/səkˈses/", pos: "N", meaning: "Sự thành công", example: "Clear communication contributed to the success of the project.", icon: "🌟" },
    { id: 45, lesson: "7", title: "Mobile technology and communication", word: "participate / participation", speak: "participate, participation", ipa: "/pɑːˈtɪsɪpeɪt/ · /pɑːˌtɪsɪˈpeɪʃn/", pos: "V / N", meaning: "Tham gia / sự tham gia", example: "Everyone should participate, because active participation improves the discussion.", icon: "🙋" },
    { id: 46, lesson: "7", title: "Mobile technology and communication", word: "etiquette", speak: "etiquette", ipa: "/ˈetɪket/", pos: "N", meaning: "Phép lịch sự; quy tắc ứng xử", example: "Good phone etiquette includes putting your device away during meals.", icon: "🎩" },
    { id: 47, lesson: "7", title: "Mobile technology and communication", word: "hang on", speak: "hang on", ipa: "/ˌhæŋ ˈɒn/", pos: "VP", meaning: "Chờ một chút; giữ máy", example: "Hang on a moment while I check the information.", icon: "⏳" },
    { id: 48, lesson: "7", title: "Mobile technology and communication", word: "ignore", speak: "ignore", ipa: "/ɪɡˈnɔː/", pos: "V", meaning: "Phớt lờ; bỏ qua", example: "It is rude to ignore a message that needs a reply.", icon: "🙈" },
    { id: 49, lesson: "10", title: "Conversation starters", word: "conversation starters", speak: "conversation starters", ipa: "/ˌkɒnvəˈseɪʃn ˌstɑːtəz/", pos: "NP", meaning: "Những câu mở đầu cuộc trò chuyện", example: "Questions about hobbies are useful conversation starters.", icon: "💬" },
    { id: 50, lesson: "10", title: "Conversation starters", word: "response", speak: "response", ipa: "/rɪˈspɒns/", pos: "N", meaning: "Câu trả lời; sự phản hồi", example: "Her friendly response encouraged me to continue speaking.", icon: "↩️" },
    { id: 51, lesson: "10", title: "Conversation starters", word: "conversationalist", speak: "conversationalist", ipa: "/ˌkɒnvəˈseɪʃənəlɪst/", pos: "N", meaning: "Người có tài trò chuyện", example: "A good conversationalist listens as much as they speak.", icon: "🗨️" },
    { id: 52, lesson: "10", title: "Conversation starters", word: "motivate", speak: "motivate", ipa: "/ˈməʊtɪveɪt/", pos: "V", meaning: "Thúc đẩy; tạo động lực", example: "A positive comment can motivate someone to join the discussion.", icon: "🚀" },
    { id: 53, lesson: "10", title: "Conversation starters", word: "celebration", speak: "celebration", ipa: "/ˌselɪˈbreɪʃn/", pos: "N", meaning: "Lễ kỷ niệm; sự ăn mừng", example: "The school celebration gave students something fun to talk about.", icon: "🎉" },
    { id: 54, lesson: "10", title: "Conversation starters", word: "abbreviation", speak: "abbreviation", ipa: "/əˌbriːviˈeɪʃn/", pos: "N", meaning: "Từ viết tắt; dạng viết tắt", example: "ASAP is an abbreviation for as soon as possible.", icon: "🔤" },
    { id: 55, lesson: "10", title: "Conversation starters", word: "emojis", speak: "emojis", ipa: "/ɪˈməʊdʒiz/", pos: "N", meaning: "Các biểu tượng cảm xúc", example: "Emojis can make a short message feel friendlier.", icon: "😀" },
    { id: 56, lesson: "10", title: "Conversation starters", word: "concise", speak: "concise", ipa: "/kənˈsaɪs/", pos: "Adj", meaning: "Súc tích; ngắn gọn", example: "Keep your text concise so the main point is easy to understand.", icon: "✂️" },
    { id: 57, lesson: "10", title: "Conversation starters", word: "origin", speak: "origin", ipa: "/ˈɒrɪdʒɪn/", pos: "N", meaning: "Nguồn gốc; xuất xứ", example: "The article explains the origin of text messaging.", icon: "🌱" },
    { id: 58, lesson: "10", title: "Conversation starters", word: "telegraph", speak: "telegraph", ipa: "/ˈtelɪɡrɑːf/", pos: "N", meaning: "Máy điện báo; điện tín", example: "The telegraph allowed people to send messages over long distances.", icon: "📡" },
    { id: 59, lesson: "10", title: "Conversation starters", word: "pros & cons", speak: "pros and cons", ipa: "/ˌprəʊz ən ˈkɒnz/", pos: "NP", meaning: "Ưu điểm và nhược điểm", example: "We discussed the pros and cons of using phones at school.", icon: "⚖️" },
    { id: 60, lesson: "10", title: "Conversation starters", word: "replace", speak: "replace", ipa: "/rɪˈpleɪs/", pos: "V", meaning: "Thay thế", example: "Video calls cannot completely replace face-to-face communication.", icon: "🔁" },
    { id: 61, lesson: "12", title: "The pros and cons of texting", word: "permanent", speak: "permanent", ipa: "/ˈpɜːmənənt/", pos: "Adj", meaning: "Vĩnh viễn; lâu dài", example: "Remember that an online message can become permanent.", icon: "♾️" },
    { id: 62, lesson: "12", title: "The pros and cons of texting", word: "pressure", speak: "pressure", ipa: "/ˈpreʃə/", pos: "N", meaning: "Áp lực; sức ép", example: "Some teenagers feel pressure to reply immediately.", icon: "😓" },
    { id: 63, lesson: "13–14", title: "Formal and informal email", word: "sophisticated", speak: "sophisticated", ipa: "/səˈfɪstɪkeɪtɪd/", pos: "Adj", meaning: "Tinh tế; phức tạp; trình độ cao", example: "The formal email used sophisticated but clear language.", icon: "🎓" },
    { id: 64, lesson: "13–14", title: "Formal and informal email", word: "contractions", speak: "contractions", ipa: "/kənˈtrækʃnz/", pos: "N", meaning: "Các dạng rút gọn", example: "Contractions such as I'm are common in informal emails.", icon: "🧷" },
    { id: 65, lesson: "13–14", title: "Formal and informal email", word: "colloquial", speak: "colloquial", ipa: "/kəˈləʊkwiəl/", pos: "Adj", meaning: "Thuộc khẩu ngữ; thông tục", example: "Colloquial expressions sound natural in friendly messages.", icon: "🗯️" },
    { id: 66, lesson: "13–14", title: "Formal and informal email", word: "imperative", speak: "imperative", ipa: "/ɪmˈperətɪv/", pos: "N / Adj", meaning: "Câu mệnh lệnh; thuộc mệnh lệnh", example: "Use an imperative such as Please reply by Friday to give a clear instruction.", icon: "📣" },
    { id: 67, lesson: "13–14", title: "Formal and informal email", word: "semi-formal language", speak: "semi formal language", ipa: "/ˌsemi ˈfɔːml ˈlæŋɡwɪdʒ/", pos: "NP", meaning: "Ngôn ngữ bán trang trọng", example: "Semi-formal language is suitable for an email to a club leader.", icon: "👔" },
    { id: 68, lesson: "13–14", title: "Formal and informal email", word: "hesitate", speak: "hesitate", ipa: "/ˈhezɪteɪt/", pos: "V", meaning: "Do dự; ngập ngừng", example: "Do not hesitate to contact me if you have questions.", icon: "🤔" },
    { id: 69, lesson: "13–14", title: "Formal and informal email", word: "exchange", speak: "exchange", ipa: "/ɪksˈtʃeɪndʒ/", pos: "N / V", meaning: "Sự trao đổi; trao đổi", example: "Our classes arranged an email exchange with students in Japan.", icon: "🔄" },
    { id: 70, lesson: "13–14", title: "Formal and informal email", word: "look forward to", speak: "look forward to", ipa: "/lʊk ˈfɔːwəd tuː/", pos: "VP", meaning: "Mong chờ; trông mong", example: "I look forward to hearing from you soon.", icon: "🔭" },
    { id: 71, lesson: "13–14", title: "Formal and informal email", word: "neutral", speak: "neutral", ipa: "/ˈnjuːtrəl/", pos: "Adj", meaning: "Trung tính; không thiên vị", example: "Choose neutral language when you do not know the reader well.", icon: "⚪" }
  ],
  situations: [
    "Mai can communicate naturally in both Vietnamese and English, so she is ____.",
    "The symbol represents an idea rather than a sound, so it is an ____.",
    "The first language a child learns at home is their ____.",
    "The museum guide speaks five languages and is therefore ____.",
    "During the live interview, an ____ translated the guest's spoken answers.",
    "A ____ works mainly with written texts between languages.",
    "This regional ____ has vocabulary that is different from the standard form.",
    "The language has no living speakers and is now ____.",
    "He kept moving his hands and feet because he tends to ____ when nervous.",
    "Her surprised facial ____ made everyone laugh.",
    "A thumbs-up is a common ____ of approval.",
    "Joy, anger, and fear are types of ____.",
    "Most people ____ the ability to communicate non-verbally.",
    "The unexplained signal seemed strange and ____.",
    "If you do not know the answer, you might ____ your shoulders.",
    "It can make people uncomfortable if you ____ at them.",
    "The ____ of the speaker's voice increased during the argument.",
    "A smile may be an ____ that someone feels welcome.",
    "Repeated clicking sounds can ____ people who are trying to focus.",
    "I ____ speaking too quickly before my partner had finished.",
    "Using open questions is a useful communication ____.",
    "Everyone spoke at once, and the meeting became complete ____.",
    "He opened his eyes wide in ____ when he heard the surprising claim.",
    "Fishing villages are common along the country's ____.",
    "Students should ____ the progress they make in a new language.",
    "She chose elegant paper and other ____ for her handwritten invitation.",
    "That informal word is popular ____ among teenagers.",
    "Dear Sir or Madam is a formal ____.",
    "A paper letter delivered by post is sometimes called ____.",
    "End the email politely and ____ with your name.",
    "The editor used software to ____ the model's photograph.",
    "We used the front camera to ____ together.",
    "Regular conversation practice is ____ for language learners.",
    "Her comments were thoughtful and ____.",
    "The poster helped raise public ____ of online safety.",
    "Icons, colour, and layout all contribute to ____.",
    "A pop-up notification can be a major ____ during study.",
    "Turn off your phone so you can ____ and improve your ____.",
    "The customer service assistant answered in a polite and professional ____.",
    "Please let Minh finish his point; do not ____ him.",
    "She used her thumb to ____ down the long article on her phone.",
    "A clear subject line is one important ____ of an effective email.",
    "Please repeat the address to ____ that we send the parcel to the right place.",
    "The presentation's ____ depended on clear teamwork and careful preparation.",
    "Every member should ____ in the role-play; active ____ helps the group learn.",
    "Putting your phone on silent in the cinema is good digital ____.",
    "____ a second; I need to find the correct file.",
    "Do not ____ a classmate who asks you a reasonable question.",
    "Questions like What music do you enjoy? are useful ____.",
    "I sent a question yesterday but have not received a ____ yet.",
    "Linh keeps discussions balanced and interesting, so she is an excellent ____.",
    "The coach used encouraging words to ____ the team before the final.",
    "Our graduation ____ included music, speeches, and photos.",
    "DIY is an ____ for do it yourself.",
    "A smiling face and a thumbs-up are popular ____ in messages.",
    "The notice is short and ____; it includes only the essential details.",
    "The historian researched the ____ of the word podcast.",
    "Before telephones, the ____ sent coded messages through wires.",
    "The class compared the ____ of online and face-to-face communication.",
    "A quick text cannot always ____ a careful conversation.",
    "A screenshot can make a supposedly temporary message ____.",
    "Some students feel social ____ to answer every notification.",
    "The article uses advanced, ____ language for an expert audience.",
    "We're and can't are examples of ____.",
    "That phrase is too ____ for a formal application.",
    "The teacher used an ____ to give a direct instruction.",
    "Use ____ when writing to an adult you know but do not know closely.",
    "If you are unsure, you may ____ before replying.",
    "The two schools began an online cultural ____.",
    "We ____ meeting your team next month.",
    "A ____ tone avoids sounding either too friendly or too formal."
  ]
};
